In [1]:
#Question 1:
import numpy as np
tab= np.array([[10,20,15],[30,40,50]])
print(tab)
list = tab.tolist()
print(list)
print(type(list))


[[10 20 15]
 [30 40 50]]
[[10, 20, 15], [30, 40, 50]]
<class 'list'>


In [2]:
#Question 2:
#avec la methode de la fonction trace
import numpy as np  
narray = np.array([[10, 15, 20],[25, 30, 35],[40, 45, 50]])  
print("Numpy Matrix is:")
print(narray) 
trace = np.trace(narray) 
print("\nTrace of given 3X3 matrix:")
print(trace)


Numpy Matrix is:
[[10 15 20]
 [25 30 35]
 [40 45 50]]

Trace of given 3X3 matrix:
90


In [3]:
#Suite question 2:
#avec la 2eme methode:
import numpy as np
matrix = np.array([[10, 15, 20],[25, 30, 35],[40, 45, 50]])
print(matrix.diagonal())
print(matrix.diagonal().sum())


[10 30 50]
90


In [4]:
#Question 3:
matrice2= np.array([[1,2],[3,5]])
print(matrice2)
print(matrice2[matrice2>2])

[[1 2]
 [3 5]]
[3 5]


In [5]:
#Question 4:
A = np.array([[3,13,30],[4,14,44],[5,15,55]])
B = np.array([[2,12,22],[1,11,11],[6,1,66]])
C= A+B
print(C)

[[  5  25  52]
 [  5  25  55]
 [ 11  16 121]]


In [6]:
#Question 5:
D=np.mean(C)
print(D) # la moyenne de toute la matrice
E=np.mean(C, axis=1) # donne la moyenne des lignes
F=np.mean(C, axis=0) # donne la moyenne des colonnes 
print(E)
print(F)
G = C - F # on soustrait de chaque element la moyenne de sa colonne 
print(G)

35.0
[27.33333333 28.33333333 49.33333333]
[ 7. 22. 76.]
[[ -2.   3. -24.]
 [ -2.   3. -21.]
 [  4.  -6.  45.]]
